<template><div><h1 id="c-di-base" tabindex="-1"><a class="header-anchor" href="#c-di-base"><span>c++ di base</span></a></h1>
<p>Quello sotto è un elenco riassuntivo di quello che abbiamo fatto al corso base.
Se non avete mai imparato prima un linguaggio di programmazione (e non siete venuti a lezione),
può avere senso guardarsi qualche tutorial su internet, ad esempio <a href="https://cplusplus.com/doc/tutorial/" target="_blank" rel="noopener noreferrer">questo</a> (alcune cose sono un po' in dettaglio)
o <a href="https://www.w3schools.com/cpp/" target="_blank" rel="noopener noreferrer">questo</a>.<br>
(non li ho provati personalmente).<br>
c++ è molto più vasto di quello che c'è scritto qua e non ha neanche senso impararselo tutto. Per questo per dubbi di vario genere bisogna far riferimento alla <a href="https://en.cppreference.com/w/" target="_blank" rel="noopener noreferrer">reference ufficiale</a>, a cui tra l'altro potete accedere anche in gara.</p>
<h2 id="struttura-di-base" tabindex="-1"><a class="header-anchor" href="#struttura-di-base"><span>Struttura di base</span></a></h2>
<p>Ogni file c++ che scriveremo avrà questa struttura:</p>
<div class="language-cpp line-numbers-mode" data-highlighter="prismjs" data-ext="cpp" data-title="cpp"><pre v-pre><code><span class="line"><span class="token macro property"><span class="token directive-hash">#</span><span class="token directive keyword">include</span> <span class="token string">&lt;bits/stdc++.h></span></span></span>
<span class="line"><span class="token keyword">using</span> <span class="token keyword">namespace</span> std<span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">int</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">//qui si mette il codice, concludendo ogni riga con un ;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="tipi" tabindex="-1"><a class="header-anchor" href="#tipi"><span>Tipi</span></a></h2>
<p>c++ ha tipi statici. Sono:</p>
<ul>
<li><code v-pre>bool</code> booleani, cioè <code v-pre>true</code> e <code v-pre>false</code> (o 1 e 0).</li>
<li><code v-pre>int</code> per rappresentare numeri interi tra -2147483648 e 2147483647 (ordine di grandezza 1e9).</li>
<li><code v-pre>long long int</code> per rappresentare numeri interi tra -9,223,372,036,854,775,808 e 9,223,372,036,854,775,807 (ordine di grandezza 1e18).</li>
<li><code v-pre>float</code> per rappresentare numeri con la virgola (da evitare per errori di precisione), massimo e minimo come gli <code v-pre>int</code>.</li>
<li><code v-pre>char</code> per singoli caratteri, si mette il carattere tra apici: <code v-pre>'a'</code>.</li>
<li><code v-pre>string</code> per liste di caratteri (parole), si mette il carattere tra doppie apici <code v-pre>&quot;stringa&quot;</code>.</li>
</ul>
<p>Per dichiarare una variabile si scrive <code v-pre>tipo nome_variabile = valore</code>.</p>
<h2 id="operatori" tabindex="-1"><a class="header-anchor" href="#operatori"><span>Operatori</span></a></h2>
<h3 id="int" tabindex="-1"><a class="header-anchor" href="#int"><span>int</span></a></h3>
<p>per fare operazioni tra int si usano i seguenti operatori:</p>
<ul>
<li><code v-pre>+</code> e <code v-pre>-</code> per addizione e sotrrazione</li>
<li><code v-pre>*</code> e <code v-pre>/</code> per moltiplicazione e divisione (intera perché tra int)</li>
<li><code v-pre>%</code> per il modulo (non importa se non sapete cos'è)</li>
</ul>
<h3 id="bool" tabindex="-1"><a class="header-anchor" href="#bool"><span>bool</span></a></h3>
<p>Gli operatori logici sono:</p>
<ul>
<li><code v-pre>&amp;&amp;</code> and logico (e).</li>
<li><code v-pre>||</code> or logico (o inclusivo).</li>
<li><code v-pre>!</code> negazione.</li>
</ul>
<h2 id="i-o" tabindex="-1"><a class="header-anchor" href="#i-o"><span>I/O</span></a></h2>
<p>Input:</p>
<div class="language-cpp line-numbers-mode" data-highlighter="prismjs" data-ext="cpp" data-title="cpp"><pre v-pre><code><span class="line">cin <span class="token operator">>></span> variabile<span class="token punctuation">;</span> <span class="token comment">// la variabile deve già esistere</span></span>
<span class="line">cin <span class="token operator">>></span> variabile1 <span class="token operator">>></span> variabile2<span class="token punctuation">;</span> <span class="token comment">// nell'input separate da uno spazio o su righe diverse</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><p>Output:</p>
<div class="language-cpp line-numbers-mode" data-highlighter="prismjs" data-ext="cpp" data-title="cpp"><pre v-pre><code><span class="line">cout <span class="token operator">&lt;&lt;</span> <span class="token string">"stringa"</span><span class="token punctuation">;</span></span>
<span class="line">cout <span class="token operator">&lt;&lt;</span> variabile1 <span class="token operator">&lt;&lt;</span> <span class="token char">' '</span> <span class="token operator">&lt;&lt;</span> variabile2<span class="token punctuation">;</span> <span class="token comment">//eventuali spazi vanno aggiunti a mano come char o stringhe</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="if" tabindex="-1"><a class="header-anchor" href="#if"><span>if</span></a></h2>
<p>La struttra dell'if è:</p>
<div class="language-cpp line-numbers-mode" data-highlighter="prismjs" data-ext="cpp" data-title="cpp"><pre v-pre><code><span class="line"><span class="token keyword">if</span> <span class="token punctuation">(</span>condizione1<span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">//codice eseguito se condizione1 è vera</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"><span class="token keyword">else</span> <span class="token keyword">if</span> <span class="token punctuation">(</span>condizione2<span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">//codice se condizione1 è falsa ma condizione2 è vera</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"><span class="token keyword">else</span> <span class="token keyword">if</span> <span class="token punctuation">(</span>condizione3<span class="token punctuation">)</span> <span class="token punctuation">{</span> <span class="token comment">//si possono mettere tanti else if quanto serve, anche nessuno</span></span>
<span class="line">    <span class="token comment">//codice se tutte le precedenti sono false ma condizione3 è vera</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"><span class="token keyword">else</span><span class="token punctuation">{</span> <span class="token comment">//se tutte le condizioni precedenti sono false</span></span>
<span class="line">    <span class="token comment">//codice</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Nota:<br>
<code v-pre>=</code> assegna un valore ad una variabile<br>
<code v-pre>==</code> controlla se due valori sono uguali<br>
<code v-pre>!=</code> controlla se sono diversi</p>
<h2 id="while-e-for" tabindex="-1"><a class="header-anchor" href="#while-e-for"><span>while e for</span></a></h2>
<p>La struttura di un while è:</p>
<div class="language-cpp line-numbers-mode" data-highlighter="prismjs" data-ext="cpp" data-title="cpp"><pre v-pre><code><span class="line"><span class="token keyword">while</span><span class="token punctuation">(</span>condizione<span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">//codice</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>la struttura del for è:</p>
<div class="language-cpp line-numbers-mode" data-highlighter="prismjs" data-ext="cpp" data-title="cpp"><pre v-pre><code><span class="line"><span class="token keyword">for</span><span class="token punctuation">(</span>inizializzazione<span class="token punctuation">;</span> condizione<span class="token punctuation">;</span> azione eseguita dopo ogni ciclo<span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">//codice</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">//esempio:</span></span>
<span class="line"><span class="token keyword">for</span><span class="token punctuation">(</span><span class="token keyword">int</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i<span class="token operator">&lt;</span>N<span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span><span class="token punctuation">{</span> <span class="token comment">//inizia con i=0, continua finché i&lt;N, ogni volta incrementa i di 1</span></span>
<span class="line">    <span class="token comment">//codice</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Per chi sa cos'è un vector posso usare anche:</p>
<div class="language-cpp line-numbers-mode" data-highlighter="prismjs" data-ext="cpp" data-title="cpp"><pre v-pre><code><span class="line">vector<span class="token operator">&lt;</span><span class="token keyword">int</span><span class="token operator">></span> vec<span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">for</span><span class="token punctuation">(</span><span class="token keyword">int</span> valore<span class="token operator">:</span> vec<span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line"></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="vector" tabindex="-1"><a class="header-anchor" href="#vector"><span>vector</span></a></h2>
<p>i vettori sono una lista di elementi a dimensione variabile.<br>
Inizializzazione:</p>
<div class="language-cpp line-numbers-mode" data-highlighter="prismjs" data-ext="cpp" data-title="cpp"><pre v-pre><code><span class="line">vector<span class="token operator">&lt;</span>tipo<span class="token operator">></span> <span class="token function">nome</span><span class="token punctuation">(</span>numero_elementi<span class="token punctuation">,</span> valore_con_cui_riempire_il_vettore<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">//esempi:</span></span>
<span class="line">vector<span class="token operator">&lt;</span><span class="token keyword">int</span><span class="token operator">></span> vec<span class="token punctuation">;</span> <span class="token comment">//sarà vuoto e di lunghezza 0</span></span>
<span class="line"><span class="token keyword">int</span> N<span class="token punctuation">;</span></span>
<span class="line">vector<span class="token operator">&lt;</span><span class="token keyword">int</span><span class="token operator">></span> <span class="token function">v</span><span class="token punctuation">(</span>N<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//sarà lungo N, con tutti gli elementi che inizialmente sono 0</span></span>
<span class="line">vector<span class="token operator">&lt;</span><span class="token keyword">long</span> <span class="token keyword">long</span><span class="token operator">></span> v2 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">}</span><span class="token punctuation">;</span> <span class="token comment">//sarà quello descritto tra parentesi: il primo elemento è 1, ...</span></span>
<span class="line"><span class="token comment">//posso anche fare vettori di vettori:</span></span>
<span class="line">vector<span class="token operator">&lt;</span>vector<span class="token operator">&lt;</span><span class="token keyword">int</span><span class="token operator">>></span> matrice<span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Per accedere/modificare un elemento:</p>
<div class="language-cpp line-numbers-mode" data-highlighter="prismjs" data-ext="cpp" data-title="cpp"><pre v-pre><code><span class="line">vector<span class="token operator">&lt;</span><span class="token keyword">int</span><span class="token operator">></span> vettore<span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">//gli indici vanno da 0 alla dimensione del vettore - 1</span></span>
<span class="line">vettore<span class="token punctuation">[</span>indice<span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">//esempi:</span></span>
<span class="line">vector<span class="token operator">&lt;</span><span class="token keyword">int</span><span class="token operator">></span> v <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">6</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">v<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">;</span> <span class="token comment">//è 5;</span></span>
<span class="line">v<span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">]</span><span class="token punctuation">;</span> <span class="token comment">//è 1;</span></span>
<span class="line">v<span class="token punctuation">[</span><span class="token number">4</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token number">17</span><span class="token punctuation">;</span> <span class="token comment">//adesso il vettore è {5, 6, 1, 2, 17};</span></span>
<span class="line">v<span class="token punctuation">[</span><span class="token number">5</span><span class="token punctuation">]</span><span class="token punctuation">;</span> <span class="token comment">//darà errore perchè l'ultimo elemento è il 4</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Per aggiungere/togliere elementi alla fine:</p>
<div class="language-cpp line-numbers-mode" data-highlighter="prismjs" data-ext="cpp" data-title="cpp"><pre v-pre><code><span class="line">vector<span class="token operator">&lt;</span><span class="token keyword">int</span><span class="token operator">></span> vettore<span class="token punctuation">;</span></span>
<span class="line">vettore<span class="token punctuation">.</span><span class="token function">push_back</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//aggiunge 10 alla fine, allungando il vettore</span></span>
<span class="line">vettore<span class="token punctuation">.</span><span class="token function">pop_back</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//toglie l'ultimo elemento, accorciando il vettore</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Per cambiare la dimesione di un vettore:</p>
<div class="language-cpp line-numbers-mode" data-highlighter="prismjs" data-ext="cpp" data-title="cpp"><pre v-pre><code><span class="line">vector<span class="token operator">&lt;</span><span class="token keyword">int</span><span class="token operator">></span> vettore<span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">int</span> nuova_dimensione<span class="token punctuation">;</span></span>
<span class="line">vettore<span class="token punctuation">.</span><span class="token function">resize</span><span class="token punctuation">(</span>nuova_dimesione<span class="token punctuation">,</span> valore_con_cui_riempire_il_vettore<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">//esempio:</span></span>
<span class="line">vettore<span class="token punctuation">.</span><span class="token function">resize</span><span class="token punctuation">(</span><span class="token number">5</span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//vettore = {-1, -1, -1, -1, -1};</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="funzioni" tabindex="-1"><a class="header-anchor" href="#funzioni"><span>funzioni</span></a></h2>
<p>Le funzioni sono un oggetto che può essere chiamato con un certo input come parametri per ritornare un certo output.<br>
Ogni funzione ha quindi il tipo della variabile che ritorna e diversi parametri, ognuno con il loro tipo e un nome.<br>
Esempi:</p>
<div class="language-cpp line-numbers-mode" data-highlighter="prismjs" data-ext="cpp" data-title="cpp"><pre v-pre><code><span class="line">tipo_da_ritornare <span class="token function">nome_funzione</span><span class="token punctuation">(</span>tipo1 parametro1<span class="token punctuation">,</span> tipo2 parametro2<span class="token punctuation">,</span> <span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">,</span> tipo3 parametro3<span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">//codice</span></span>
<span class="line">    <span class="token keyword">return</span> var<span class="token punctuation">;</span> <span class="token comment">//dove var è tipo_da_ritornare</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">int</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">    tipo_da_ritornare var<span class="token punctuation">;</span></span>
<span class="line">    var <span class="token operator">=</span> <span class="token function">nome_funzione</span><span class="token punctuation">(</span>parametri<span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//var avrà il valore ritornato</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">//se non ritorna valori uso il tipo void</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">void</span> <span class="token function">funzione</span><span class="token punctuation">(</span>parametri<span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">//codice</span></span>
<span class="line">    <span class="token keyword">return</span><span class="token punctuation">;</span> <span class="token comment">//non ritorno niente</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">//esempi:</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">int</span> <span class="token function">sum</span><span class="token punctuation">(</span><span class="token keyword">int</span> a<span class="token punctuation">,</span> <span class="token keyword">int</span> b<span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">int</span> c<span class="token operator">=</span> a<span class="token operator">+</span>b<span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">return</span> c<span class="token punctuation">;</span></span>
<span class="line">    <span class="token comment">//o return a+b</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">int</span> <span class="token function">somma_di_tanti_numeri</span><span class="token punctuation">(</span>vector<span class="token operator">&lt;</span><span class="token keyword">int</span><span class="token operator">></span>vec<span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">int</span> sol <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">int</span> n <span class="token operator">=</span> vec<span class="token punctuation">.</span><span class="token function">size</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">for</span><span class="token punctuation">(</span><span class="token keyword">int</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i<span class="token operator">&lt;</span>n<span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">        sol <span class="token operator">+=</span> vec<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    <span class="token keyword">return</span> sol<span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">//posso chiamare una funzione dentro un'altra in modo ricorsivo</span></span>
<span class="line"><span class="token keyword">int</span> <span class="token function">fibonacci</span><span class="token punctuation">(</span><span class="token keyword">int</span> n<span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">if</span><span class="token punctuation">(</span>n<span class="token operator">==</span><span class="token number">1</span> <span class="token operator">||</span> n<span class="token operator">==</span><span class="token number">2</span><span class="token punctuation">)</span> <span class="token keyword">return</span> <span class="token number">1</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">return</span> <span class="token function">fibonacci</span><span class="token punctuation">(</span>n<span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token operator">+</span><span class="token function">fibonacci</span><span class="token punctuation">(</span>n<span class="token operator">-</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="stl" tabindex="-1"><a class="header-anchor" href="#stl"><span>stl</span></a></h2>
<h3 id="funzioni-1" tabindex="-1"><a class="header-anchor" href="#funzioni-1"><span>funzioni</span></a></h3>
<p><code v-pre>sort()</code> serve per ordinare un vettore in ordine crescente. Si può anche passare come parametro un comparatore per cambiare ordinarli secondo un altro criterio.</p>
<div class="language-cpp line-numbers-mode" data-highlighter="prismjs" data-ext="cpp" data-title="cpp"><pre v-pre><code><span class="line">vector<span class="token operator">&lt;</span><span class="token keyword">int</span><span class="token operator">></span> vec<span class="token punctuation">;</span></span>
<span class="line"><span class="token function">sort</span><span class="token punctuation">(</span>vec<span class="token punctuation">.</span><span class="token function">begin</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> vec<span class="token punctuation">.</span><span class="token function">end</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//ordina in ordine crescente</span></span>
<span class="line"></span>
<span class="line">vector<span class="token operator">&lt;</span>string<span class="token operator">></span> vec2<span class="token punctuation">;</span></span>
<span class="line"><span class="token function">sort</span><span class="token punctuation">(</span>vec2<span class="token punctuation">.</span><span class="token function">begin</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> vec2<span class="token punctuation">.</span><span class="token function">end</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//ordina le stringhe lessicograficamente (come nel dizionario)</span></span>
<span class="line"></span>
<span class="line">vector<span class="token operator">&lt;</span>pair<span class="token operator">&lt;</span><span class="token keyword">int</span><span class="token punctuation">,</span> <span class="token keyword">int</span><span class="token operator">>></span> vec3<span class="token punctuation">;</span> </span>
<span class="line"><span class="token function">sort</span><span class="token punctuation">(</span>vec3<span class="token punctuation">.</span><span class="token function">begin</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> vec3<span class="token punctuation">.</span><span class="token function">end</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//anche in questo caso in ordine lessicografico</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">bool</span> <span class="token function">comp</span><span class="token punctuation">(</span><span class="token keyword">int</span> a<span class="token punctuation">,</span> <span class="token keyword">int</span> b<span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">return</span> a <span class="token operator">></span> b<span class="token punctuation">;</span> <span class="token comment">//posso definire un mio comparatore (quello standard è a &lt; b)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"><span class="token function">sort</span><span class="token punctuation">(</span>vec<span class="token punctuation">.</span><span class="token function">begin</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> vec<span class="token punctuation">.</span><span class="token function">end</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> comp<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//ordina in modo decrescente</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>swap</code> serve per scambiare il valore di due variabili in O(1).</p>
<div class="language-cpp line-numbers-mode" data-highlighter="prismjs" data-ext="cpp" data-title="cpp"><pre v-pre><code><span class="line"><span class="token keyword">int</span> a <span class="token operator">=</span> <span class="token number">2</span><span class="token punctuation">;</span> <span class="token keyword">int</span> b <span class="token operator">=</span> <span class="token number">3</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token function">swap</span><span class="token punctuation">(</span>a<span class="token punctuation">,</span> b<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//adesso a = 3 e b = 2;</span></span>
<span class="line"></span>
<span class="line">vector<span class="token operator">&lt;</span><span class="token keyword">int</span><span class="token operator">></span> v1<span class="token punctuation">;</span> vector<span class="token operator">&lt;</span><span class="token keyword">int</span><span class="token operator">></span> v2<span class="token punctuation">;</span></span>
<span class="line"><span class="token function">swap</span><span class="token punctuation">(</span>v1<span class="token punctuation">,</span> v2<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//posso swappare tutte le strutture della stl in O(1)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>lower_bound</code> e <code v-pre>upper_bound</code> servono per trovare in un vettore il primo elemento &gt;= o &gt; di un dato valore.</p>
<div class="language-cpp line-numbers-mode" data-highlighter="prismjs" data-ext="cpp" data-title="cpp"><pre v-pre><code><span class="line">vector<span class="token operator">&lt;</span><span class="token keyword">int</span><span class="token operator">></span> vec<span class="token punctuation">;</span></span>
<span class="line"><span class="token function">lower_bound</span><span class="token punctuation">(</span>vec<span class="token punctuation">.</span><span class="token function">begin</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> vec<span class="token punctuation">.</span><span class="token function">end</span><span class="token punctuation">(</span><span class="token punctuation">)</span> valore<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//ottiene il primo elemento >= del valore complessità: O(logN)</span></span>
<span class="line"><span class="token function">lower_bound</span><span class="token punctuation">(</span>vec<span class="token punctuation">.</span><span class="token function">begin</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> vec<span class="token punctuation">.</span><span class="token function">end</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> valore<span class="token punctuation">)</span> <span class="token operator">-</span> vec<span class="token punctuation">.</span><span class="token function">begin</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//per trovare l'indice dell'elemento trovato complessità: O(logN)</span></span>
<span class="line"><span class="token function">upper_bound</span><span class="token punctuation">(</span>vec<span class="token punctuation">.</span><span class="token function">begin</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> vec<span class="token punctuation">.</span><span class="token function">end</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> valore<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//ottiene il primo elemento > del valore complessità: O(logN)</span></span>
<span class="line"><span class="token function">upper_bound</span><span class="token punctuation">(</span>vec<span class="token punctuation">.</span><span class="token function">begin</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> vec<span class="token punctuation">.</span><span class="token function">end</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> valore<span class="token punctuation">)</span> <span class="token operator">-</span> vec<span class="token punctuation">.</span><span class="token function">begin</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//per trovare l'indice dell'elemento trovato complessità: O(logN)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="data-structures" tabindex="-1"><a class="header-anchor" href="#data-structures"><span>data structures</span></a></h3>
<h4 id="priority-queue" tabindex="-1"><a class="header-anchor" href="#priority-queue"><span>priority_queue</span></a></h4>
<p>Permette di trovare il più grande elemento.</p>
<div class="language-cpp line-numbers-mode" data-highlighter="prismjs" data-ext="cpp" data-title="cpp"><pre v-pre><code><span class="line">priority_queue<span class="token operator">&lt;</span>tipo<span class="token operator">></span> pq<span class="token punctuation">;</span></span>
<span class="line">pq<span class="token punctuation">.</span><span class="token function">top</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// elemento più grande complessità: O(1)</span></span>
<span class="line">pq<span class="token punctuation">.</span><span class="token function">pop</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// elimina l'elemento più grande complessità: O(logN)</span></span>
<span class="line">pq<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// aggiunge un elemento complessità: O(logN)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="set" tabindex="-1"><a class="header-anchor" href="#set"><span>set</span></a></h4>
<p>Data structure in cui non sono ammessi duplicati e gli elementi sono ordinati.<br>
Non posso accedere ad un singolo elemento con un indice, ma posso contrallare se c'è un elemento e il primo elemento più grande di un certo valore.</p>
<div class="language-cpp line-numbers-mode" data-highlighter="prismjs" data-ext="cpp" data-title="cpp"><pre v-pre><code><span class="line">set<span class="token operator">&lt;</span>tipo<span class="token operator">></span> s<span class="token punctuation">;</span></span>
<span class="line">s<span class="token punctuation">.</span><span class="token function">insert</span><span class="token punctuation">(</span>valore<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//inserisce un elemento nel set complessità: O(logN)</span></span>
<span class="line">s<span class="token punctuation">.</span><span class="token function">erase</span><span class="token punctuation">(</span>valore<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//elimina un elemnto complessità: O(logN)</span></span>
<span class="line"><span class="token operator">*</span>s<span class="token punctuation">.</span><span class="token function">begin</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//primo elemento complessità: O(1)</span></span>
<span class="line">s<span class="token punctuation">.</span><span class="token function">end</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//punta a dopo l'ultimo elemento, leggere sotto per dettagli complessità: O(1)</span></span>
<span class="line"><span class="token operator">*</span>s<span class="token punctuation">.</span><span class="token function">lower_bound</span><span class="token punctuation">(</span>valore<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//ottiene il primo elemento >= del valore complessità: O(logN)</span></span>
<span class="line"><span class="token operator">*</span>s<span class="token punctuation">.</span><span class="token function">upper_bound</span><span class="token punctuation">(</span>valore<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//ottiene il primo elemento > del valore complessità: O(logN)</span></span>
<span class="line">s<span class="token punctuation">.</span><span class="token function">count</span><span class="token punctuation">(</span>valore<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//conta il numero di elementi uguali al valore </span></span>
<span class="line"><span class="token comment">//count nel set può ritornare solo 0 e 1 complessità: O(logN)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Se voglio accedere ad elementi vicini ad <code v-pre>s.begin()</code>, <code v-pre>s.end()</code>, <code v-pre>s.lower_bound()</code> o <code v-pre>s.upper_bound</code>, basta salvarseli in una variabile <code v-pre>auto</code> (ad esempio <code v-pre>auto it = s.begin()</code>) e poi ci si può spostare con <code v-pre>++</code> e <code v-pre>--</code> (tipo <code v-pre>it++</code> o <code v-pre>it--</code>). A quel punto si può leggere l'elemento in quella posizione con <code v-pre>*</code> (ad esempio <code v-pre>*it</code>).<br>
Se siete curiosi questo succede perché queste funzioni ritornano un iteratore, potete trovare informazioni su internet, diciamo che però adesso non ci servono.</p>
<h4 id="map" tabindex="-1"><a class="header-anchor" href="#map"><span>map</span></a></h4>
<p>Struttura dati in cui ad ogni elemento è associata una chiave, con cui posso accederci (un po' come l'indice nel vettore ma la chiave può essere qualuqnue cosa).<br>
All'interno le coppie chiave, valore sono ordinati in ordine crescente in base alla chiave.</p>
<div class="language-cpp line-numbers-mode" data-highlighter="prismjs" data-ext="cpp" data-title="cpp"><pre v-pre><code><span class="line">map<span class="token operator">&lt;</span>tipo_chiave<span class="token punctuation">,</span> tipo_valore<span class="token operator">></span> mp<span class="token punctuation">;</span></span>
<span class="line">mp<span class="token punctuation">[</span>chiave<span class="token punctuation">]</span> <span class="token operator">=</span> valore<span class="token punctuation">;</span> <span class="token comment">//sia per creare una coppia chiave valore che per cambiare il valore o altro complessità: O(logN)</span></span>
<span class="line"><span class="token comment">//per ciclare sulle coppie chiave, valore posso fare:</span></span>
<span class="line"><span class="token keyword">for</span><span class="token punctuation">(</span><span class="token keyword">auto</span> <span class="token punctuation">[</span>c<span class="token punctuation">,</span> v<span class="token punctuation">]</span><span class="token operator">:</span> mp<span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">//faccio qualcosa con c e v</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line">mp<span class="token punctuation">.</span><span class="token function">count</span><span class="token punctuation">(</span>chiave<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//posso controllare il numero di elementi con una data chiave complessità: O(logN)</span></span>
<span class="line">mp<span class="token punctuation">.</span><span class="token function">insert</span><span class="token punctuation">(</span><span class="token punctuation">{</span>chiave<span class="token punctuation">,</span> valore<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//posso aggiungere elementi così complessità: O(logN)</span></span>
<span class="line">mp<span class="token punctuation">.</span><span class="token function">erase</span><span class="token punctuation">(</span><span class="token punctuation">{</span>chiave<span class="token punctuation">,</span> valore<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//ed eliminarli così</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="unordered-multi" tabindex="-1"><a class="header-anchor" href="#unordered-multi"><span>unordered-, multi-</span></a></h4>
<p>Sia per i set che per le map esistono delle varianti.<br>
<code v-pre>unordered_</code> vuol dire che gli elementi non sono ordinati. La complessità delle operazioni scende a O(1) ammortizzato.<br>
<code v-pre>multi</code> vuol dire che possono essere più elementi con lo stesso valore (nel <code v-pre>multiset</code>) o chiave (<code v-pre>multimap</code>). Nelle <code v-pre>multimap</code> non posso usare <code v-pre>mp[chiave]</code>.</p>
<h4 id="queue-stack-list" tabindex="-1"><a class="header-anchor" href="#queue-stack-list"><span>queue, stack, list</span></a></h4>
<p>Con la queue aggiungo da un lato tolgo/vedo dall'altro (come una coda).</p>
<div class="language-cpp line-numbers-mode" data-highlighter="prismjs" data-ext="cpp" data-title="cpp"><pre v-pre><code><span class="line">queue<span class="token operator">&lt;</span>tipo<span class="token operator">></span> q<span class="token punctuation">;</span></span>
<span class="line">q<span class="token punctuation">.</span><span class="token function">front</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//elemento davanti complessità: O(1)</span></span>
<span class="line">q<span class="token punctuation">.</span><span class="token function">pop</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//elimino elemento davanti complessità: O(1)</span></span>
<span class="line">q<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>valore<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//aggiungo elemento in fondo complessità: O(1)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Con lo stack aggiungo e tolgo dallo stesso lato (come una pila di libri).</p>
<div class="language-cpp line-numbers-mode" data-highlighter="prismjs" data-ext="cpp" data-title="cpp"><pre v-pre><code><span class="line">stack<span class="token operator">&lt;</span><span class="token keyword">int</span><span class="token operator">></span> st<span class="token punctuation">;</span></span>
<span class="line">st<span class="token punctuation">.</span><span class="token function">top</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//elemento in cima complessità: O(1)</span></span>
<span class="line">st<span class="token punctuation">.</span><span class="token function">pop</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//elimino elemento in cima complessità: O(1)</span></span>
<span class="line">st<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>valore<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//aggiungo elemento in cima complessità: O(1)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Con la deque aggiungo e tolto da entrambi i lati, ma posso anche accedere agli elemnti attraverso gli indici!</p>
<div class="language-cpp line-numbers-mode" data-highlighter="prismjs" data-ext="cpp" data-title="cpp"><pre v-pre><code><span class="line">deque<span class="token operator">&lt;</span><span class="token keyword">int</span><span class="token operator">></span> dq<span class="token punctuation">;</span></span>
<span class="line">dq<span class="token punctuation">.</span><span class="token function">front</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//elemento davanti complessità: O(1)</span></span>
<span class="line">dq<span class="token punctuation">.</span><span class="token function">push_front</span><span class="token punctuation">(</span>valore<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//aggiungo elemento davanti: O(1)</span></span>
<span class="line">dq<span class="token punctuation">.</span><span class="token function">pop_front</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//tolgo elemenot davanti complessità: O(1)</span></span>
<span class="line">dq<span class="token punctuation">.</span><span class="token function">back</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//elemento dietro complessità: O(1)</span></span>
<span class="line">dq<span class="token punctuation">.</span><span class="token function">push_back</span><span class="token punctuation">(</span>valore<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//aggiungo elemento dietro: O(1)</span></span>
<span class="line">dq<span class="token punctuation">.</span><span class="token function">pop_back</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//tolgo elemenot dietro complessità: O(1)</span></span>
<span class="line">dq<span class="token punctuation">[</span>indice<span class="token punctuation">]</span><span class="token punctuation">;</span> <span class="token comment">//accede con gli indici (come i vettori) complessità: O(1)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


